package com.udacity.examples.popularmovie.utils;

import com.udacity.examples.popularmovie.data.Movie;
import com.udacity.examples.popularmovie.data.Review;
import com.udacity.examples.popularmovie.data.Video;

/**
 * Created by Mahmoud Emam on 2/25/18.
 */

public class MockMoviesUtils {
    public static final Movie[] MOCK_MOVIES = {
            new Movie(7007, 198663, false, 7f, "The Maze Runner", 456.70939, "/coss7RgL0NH6g4fC2s5atvf3dFO.jpg", "en", "The Maze Runner", new int[] {28, 9648, 878, 53}, "/lkOZcsXcOLZYeJ2YxJd3vSldvU4.jpg", false, "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.", "2014-09-10"),
            new Movie(125, 441614, false, 4.7f, "Loving", 432.74586, "/6uOMVZ6oG00xjq0KQiExRBw2s3P.jpg", "es", "Amar", new int[] {10749}, "/iBM6zvlOmcfodGhUa36sy7pM2Er.jpg", false, "Laura and Carlos love each other as if every day was the last, and perhaps that first love intensity is what will tear them apart a year later.", "2017-04-21"),
            new Movie(520, 337167, false, 6.5f,"Fifty Shades Freed", 429.545422, "/jjPJ4s3DWZZvI4vw8Xfi4Vqa1Q8.jpg", "en", "Fifty Shades Freed", new int[] {18, 10749}, "/9ywA15OAiwjSTvg3cBs9B7kOCBF.jpg", false, "Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.", "2018-02-07"),
            new Movie(4248, 284053, false, 7.4f, "Thor: Ragnarok", 318.100542, "/oSLd5GYGsiGgzDPKTwQh7wamO8t.jpg", "en", "Thor: Ragnarok", new int[] {878, 28, 12, 35, 14}, "/5wNUJs23rT5rTBacNyf5h83AynM.jpg", false, "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the prophecy of destruction to his homeworld and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.", "2017-10-25"),
            new Movie(1473, 284054, false, 7.4f, "Black Panther", 290.142649, "/bLBUCtMQGJclH36clliPLmljMys.jpg", "en", "Black Panther", new int[] {28, 12, 14, 878}, "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg", false, "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war.", "2018-02-13")
    };

    public static final Video[] MOCK_VIDEOS = {
            new Video("\"Have a Donut\" Clip - Zootopia", "zQ2XkyDTW34", "Clip"),
            new Video("Zootopia US Teaser Trailer", "g9lmhBYB11U", "Trailer"),
            new Video("\"Elephant in the Room\" Clip - Zootopia", "b8hYj0ROMo4", "Clip"),
            new Video("Zootopia Official US Trailer #2", "jWM0ct-OLsM", "Trailer"),
            new Video("Zootopia Official US Sloth Trailer", "bY73vFGhSVk", "Trailer")
    };

    public static final Review[] MOCK_REVIEWS = {
            new Review("Andres Gomez", "One of the best movies Disney has created in the last years. Smart plot with a great background topic talking about the differences, stereotypes, prejudices and joining the tendency of giving women more important roles.\r\n\r\nIt has still several gaps to fill and enhance on the latest point but it is, IMHO, a milestone in the right direction.\r\n\r\nThe characters work pretty well and it is funny when needed and not too full of cheesy songs."),
            new Review("Reno", "> Try everything (but differently). So Disney has done it again.\r\n\r\nThis beautiful animation came to exist because of coming together of the directors of 'Tangled' and 'Wreck-it-Ralp'. It is Disney who had once again done it, since their rival Pixer is going down in a rapid speed. As a Disney fan since my childhood, I'm very happy for their success in live-shot films and animations, especially for this one.\r\n\r\nOkay, since the revolution of 3D animation over 20 years ago after overthrowing the 2D animation, most of the big productions like Disney, Pixer and Dreamworks with few others never failed to deliver. Believe me, I was not interested in this film when I first saw the teaser and trailer. But they have done great promotions and so the film did awesomely at screens worldwide. I was totally blown away after seeing it, Disney's another unique universal charactered story. From the little children to the grown ups, everybody definitely going to enjoy it.\r\n\r\nAll kinds of animals coming together happens only in cinemas, and that too mostly in animations. But todays kids are very sharp who ask lots of questions, so they had a fine explanation for the doubts regarding putting animals in a same society. It was like the United States, where everyone came from different continents and represents different race. And so in this film every animal came from different land to live together peacefully in a city called Zootopia.\r\n\r\nSo the story begins when Judy the rabbit follows her dream to become a police officer in Zootopia. There she meets Nick the fox, who are actually arch-rival species in the wild, but it was thousands of years ago before adapting the civilisation. So trust is what not promised between them, but they're forced to work together after a small missing person case becomes their prime agenda. Solving the mystery is what brings the end to this wonderful tale.\r\n\r\nThese days animations are not just concentrated on comedies, trying to get us emotionally as well. Maybe that's how they're grabbing the adult audience, especially the families. Shakira's cameo was the highlight, and her song 'Try Everything' helped the get attention from all the corners.\r\n\r\nThe Oscars was concluded just a couple of months ago, but it already feels like the fever is gripping again for the next edition and looks like this film is leading the way for the animation category. I know it's too early, but I hope it wins it. And finally a request for the Disney, bring it on a sequel as soon as possible.\r\n\r\n8/10"),
            new Review("whatowatch", "Zootopia is the latest family animation movie from Disney about a young bunny determined to be a cop at all costs  – in a land where only 'predators' are cops, she would be the first ‘prey’ cop. Seriously? Anyway, she puts on the hard work and makes it to the land where anything is possible.\r\n\r\nZootopia makes some good real life comparisons: Zootopia itself seems to look like New York, even including a hustle by a sly fox.  Racism seems to be ever present in both color and speech. But the best thing about Zootopia is Judy’s positive attitude and relentless determination to succeed.\r\n\r\nThe animation is as good as a Pixar animation – perfectly made  – and the story is well told, full of action scenes and funny moments. Kids will definitely love this one and grown up kids will enjoy the deep thought provoking tones set in this  \r\n\r\nThe best performance in this movie arguably comes from Police Chief Bogo whose voice is played by Idris Elba. His performance should earn him an Oscar this year! No wonder it has grossed 1 Billion dollars worldwide despite little marketing. \r\n\r\nRated 9 out of 10 only because we cannot give it a 10."),
            new Review("Austin Singleton", "A great movie with a great message. Read my full review here.\r\n\r\nhttp://www.hweird1reviews.com/allreviews/zootopia-review"),
            new Review("Gimly", "_Zootopia_ leans pretty hard on a few tropes that I absolutely detest, but even I can't deny that this animated family movie succeeds spectacularly at what it set out to do: Entertain all audiences, young & old, and deliver an important moral centre without detracting from its engaging plot. Something rarely achieved by the medium outside of Pixar. And even Pixar has had a few missteps the past years.\r\n\r\n_Final rating:★★★½ - I strongly recommend you make the time._"),
            new Review("Per Gunnar Jonsson", "This is a really, really good animated family movie. It is a perfect blend of funny characters, decent story and little jokes spread around in the animation.\r\n\r\nAlmost all characters are very likable and funny, each in a different way. The actual story has quite a bit of suspense (for an animated family film) while still being sufficiently light and funny. Actually it is kind of two stories. One is the story of Judy Hopps fighting to prove herself as a police officer and the other is the more sinister evil plot that she attempts to unravel.\r\n\r\nThe movie moves at a good enough speed leaving enough room to both tell the story itself and inserting jokes and comical situations. The two bureaucratic sloths were quite fun already in their first scenes but the last scene with them at the very end of the movie was absolutely hilarious.\r\n\r\nThe animation itself was certainly adequate although I sometimes miss the old hand drawn animations from Walt Disney.\r\n\r\nOverall, one of the better, if not the best, animated movie I have watched in quite a while."),
            new Review("mattwilde123", "This film is named 'Zootopia' in the US but the title was changed when it was shown in the UK. I thought it is a very good children's film. Very well animated. Colourful. Really cute animals.\r\n\r\nIt is a great parable about tolerance and racism which could be seen as a mirror to the xenophobia in society today. The story is of a rabbit called Judy Hopps who overcomes diversity to become a police officer in the city of Zootropolis (Zootopia). This is a very tough city full of crime and only strong predators take charge. Judy must help to solve the case of predators disappearing around the city but needs to fight her colleagues' prejudices at the same time.\r\n\r\nThe jokes are funny and the story is intriguing. The film contains lots of references to other films which will keep viewers of all ages happy (including a very funny Breaking Bad spoof).\r\nThe voice acting is very good and each actor perfectly adds to their character.\r\n\r\n★★★★"),
            new Review("Neeraj", "Zootopia is an allegorical tale which subtly takes on vast topics like racism, politics and society. It explores these underlying philosophical themes in a rather humorous manner! Everything, right from the characters to the storyline, is just top notch!\r\n\r\nIt’s similar to George Orwell’s Animal Farm, just the underlying issues are different in this one. It’s definitely worth watching! \r\n\r\nOverall, Zootopia is a brilliant movie! I would give it a rating of** 4/5**")
    };
}
